getporter/helm-mixin

cmd/helm/main.go
cmd/helm/upgrade.go
pkg/helm/upgrade.go
pkg/helm/upgrade_test.go

This represents the naive/mostly-copy-paste implementation.  
As you'll note, `upgrade.go` looks nearly identical to the pre-existing `install.go`, just with a slightly different cmd base.  We could extract shared logic into a new file that both could use (`upsert.go`?) which has a cmd base of `helm upgrade`, with, conditionally, `--install`, depending on caller (`install.go` vs `upgrade.go`).  Should we go this route here?  And/or a diff approach?

feat(*): implement upgrade

---

pkg/helm/install.go
pkg/helm/install_test.go

Adds ability to set `--wait` on the `helm install` command.  See docs in https://github.com/helm/helm/blob/master/docs/helm/helm_install.md

feat(install.go): add wait flag

---

pkg/helm/upgrade.go
pkg/helm/upgrade_test.go

- Removes invalid `replace` flag from the upgrade action
- Adds `reuse-values`, `reset-values` and `wait` flags
- Refactors the upgrade test to support varying flag options
I still hope to refactor/consolidate similar logic between install and upgrade, but wanted to get this PR up while testing upgrade in porter.

feat(upgrade): remove invalid replace flag, add further flags

---

pkg/helm/install.go
pkg/helm/install_test.go
pkg/helm/packrd/packed-packr.go
pkg/helm/status.go
pkg/helm/status_test.go
pkg/helm/step.go
pkg/helm/uninstall.go
pkg/helm/uninstall_test.go
pkg/helm/upgrade.go
pkg/helm/upgrade_test.go

This updates the helm mixin to match the latest change in porter where all the properties related to a step go _under_ the mixin name. See https://github.com/deislabs/porter/pull/182 for all the details.

Rearrange schema

---

pkg/helm/schema/helm.json
pkg/helm/testdata/schema.json

Porter will handle converting these when it merges the schema. The library used by VS Code doesn't handle ids properly.

Use relative schema references

---

Makefile

I need this for local testing on Mac in order to be able to do
```
RUNTIME_PLATFORM=darwin make install
```
and then a 
```
porter run --action=install
```
on a bundle that users the Helm mixin
see also https://github.com/deislabs/porter-azure/pull/15

allow override for runtime platform in makefile

---

cmd/helm/main.go

Here's an example of why we want this:
```
Uninstall MySQL
Error: uninstall.0.helm: releases is required
* uninstall.0.helm: Additional property name is not allowed
Usage:
helm uninstall [flags]
Flags:
-h, --help   help for uninstall
Global Flags:
--debug   Enable debug logging
err: uninstall.0.helm: releases is required
* uninstall.0.helm: Additional property name is not allowed
Error: mixin execution failed: exit status 1
```
The helptext should only be printed when the command was called incorrectly. Otherwise it's just noise. We have this turned on for other commands (like porter) but just never got around flipping the switch for this one too.

Do not print helptext on runtime errors

---

pkg/helm/install_test.go
pkg/helm/schema/helm.json
pkg/helm/testdata/install-input.yaml
pkg/helm/testdata/schema.json
pkg/helm/testdata/upgrade-input.yaml
pkg/helm/upgrade_test.go

Updates the `set` portion of this mixin's schema to allow for various types.
Credit to @carolynvs for the change/fix.  See https://github.com/deislabs/porter-helm/pull/28#issuecomment-478072977 
Tested via `make test-cli` from https://github.com/deislabs/porter/pull/246

fix(schema): update set schema to allow for various types

---

Makefile
azure-pipelines.yml

This removes the unnecessary `helm-runtime-linux-amd64` binary from the build matrix.
While I was in there, I standardized the Makefile with some of the other changes that we had from the porter **mixin.mk` so it's easier to read.

Do not publish extra runtime binary

---

pkg/helm/upgrade.go
pkg/helm/upgrade_test.go

Adds `--install` to the `helm upgrade ...` command as invoked by an upgrade step using this mixin, to create a release if for some reason it didn't yet pre-exist.
Closes https://github.com/deislabs/porter-helm/issues/45

feat(upgrade.go): add --install to helm upgrade invocation

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
Gopkg.lock
Makefile
README.md
REVIEWING.md

Update all the supporting repository pages: readme, CoC, contributing, etc to match Porter and reference Porter where we can.
This is a part of https://github.com/deislabs/porter/issues/675.

Standardize repository window dressing

---

pkg/helm/build.go
pkg/helm/build_test.go
pkg/helm/init_test.go

Bumps the default helm client version to the next major release (or, last stable variant thereof), [v2.15.2](https://github.com/helm/helm/releases/tag/v2.15.2), which came with some API updates for compatibility with more recent versions of k8s.
Fixes the issue mentioned in https://github.com/deislabs/porter-helm/issues/53#issue-551431835.
Closes https://github.com/deislabs/porter-helm/issues/53

chore(build.go): bump helm client to v2.15.2

---

examples/mysql/porter.yaml

A few updates to this example bundle:
- Set the default registry to `getporter`
- Set a chart version (latest stable)
- Set a default for `mysql-user`
This example was obviously lifted from the OG version in the main porter repo and although I don't like the duplication, I like at least one simple example to live alongside each mixin repo.

chore(examples): update the mysql example

---

pkg/kubernetes/kubernetes.go

This will allow authentication and trigger the oauth negotiation for clusters that are protected by `oidc` or `azure`

Added `client-go/plugin/pkg/client/auth`

---

go.mod
go.sum
pkg/helm/action.go
pkg/helm/execute_test.go
pkg/helm/version.go

Do not assume that mixin arguments and flags should be passed as a quoted string
to the cli. Require that they are wrapped in quotes instead and
otherwise split on space to pass them separately.
See https://github.com/deislabs/porter/pull/931 for how this works.

Split mixin arguments

---

pkg/helm/build.go
pkg/helm/build_test.go
pkg/helm/testdata/build-input-with-invalid-client-version.yaml
pkg/helm/testdata/build-input-with-supported-client-version.yaml
pkg/helm/testdata/build-input-with-unsupported-client-version.yaml

* adds functionality to verify the client version supplied via mixin config satisfies semver constraints
Depends on https://github.com/deislabs/porter/pull/989 for build error to actually stop build.
Closes https://github.com/deislabs/porter-helm/issues/67

feat(build.go): restrict to client version of v2.x.x

---

go.mod
go.sum
pkg/helm/execute.go
pkg/helm/install.go
pkg/helm/outputs.go
pkg/helm/upgrade.go

* Defer to the namespace value set on the step, unless it is set explicitly on a given output
This fixes a regression that came in recently wherein we stopped using the step namespace and only used the namespace value set on a given output (and defaults to `default` if not set.)  However, the precedent when using this mixin was for outputs to inherit the step namespace.

fix(*): fix namespace regression

---

pkg/helm/outputs.go

Removes the single quotes around a k8s output (also done in the k8s mixin: https://github.com/getporter/porter/pull/1227/files#diff-ee3f112df3df9e8ec5f3f9f98618987fR97)
I originally had designs for a refactor to enable sharing the same bit of code but wanted to get the fix in while other tasks take priority.
Closes https://github.com/deislabs/porter-helm/issues/71

fix(outputs.go): remove single quotes from k8s outputs

---

README.md
examples/mysql/porter.yaml
pkg/helm/build.go
pkg/helm/build_test.go
pkg/helm/helm.go
pkg/helm/testdata/build-input-with-valid-config-multi-repos.yaml
pkg/helm/testdata/build-input-with-valid-config.yaml

* Reference the new stable chart location
* Use the version of helm 2 that defaults to the new stable chart repository
Fixes #80 
I will immediately cut a new release after this is merged.

Update helm to fix stable chart move

---

README.md
cmd/helm/build.go
cmd/helm/install.go
cmd/helm/invoke.go
cmd/helm/main.go
cmd/helm/schema.go
cmd/helm/uninstall.go
cmd/helm/upgrade.go
cmd/helm/version.go
examples/mysql/porter.yaml
go.mod
pkg/helm/helm.go
pkg/helm/helpers.go
pkg/helm/version.go
pkg/helm/version_test.go

* Keep the binary and mixin yaml the same, so people can use `helm: ...` in the porter manifests still
* The mixin source code is moving to get.porter.sh/mixins/helm2 so that it doesn't appear to be THE helm mixin.
* Tell people to use MChorfa's helm3 mixin.
TODO:

Publicly rename the mixin to helm2
